fix: clean up shell scripts

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -17,20 +17,20 @@ runs:
       id: get-hugo-version
       run: |
         ## Get the Latest Hugo Version
-        latest_version="$(curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/')"
-        echo HUGO_LATEST_VERSION="$latest_version" >> $GITHUB_ENV
-        echo ":rocket: Latest Hugo Version: $latest_version" >> $GITHUB_STEP_SUMMARY
+        latest_version="$(curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"v([^"]+)".*/\1/' || echo "Error getting Hugo version")"
+        echo "HUGO_LATEST_VERSION=\"$latest_version\"" >> "$GITHUB_ENV"
+        echo ":rocket: Latest Hugo Version: $latest_version" >> "$GITHUB_STEP_SUMMARY"
     - name: Get Netlify TOML Version
       id: get-netlify-toml-version
       shell: bash
       run: |
           ## Get the Netlify TOML Version
           if [ -f "${{ inputs.netlify-toml-path }}" ]; then
-            current_version="$(sed <"${{ inputs.netlify-toml-path }}" -n 's/^HUGO_VERSION = //p' | tr -d "\"")"
-            echo NETLIFY_CURRENT_VERSION="$current_version" >> $GITHUB_ENV
-            echo "Current Netlify TOML Version: $current_version" >> $GITHUB_STEP_SUMMARY
+            current_version="$(sed -r <"${{ inputs.netlify-toml-path }}" -n 's/^HUGO_VERSION\s*=\s*//p' | tr -d "\"")"
+            echo "NETLIFY_CURRENT_VERSION=\"$current_version\"" >> "$GITHUB_ENV"
+            echo "Current Netlify TOML Version: $current_version" >> "$GITHUB_STEP_SUMMARY"
           else
-            echo "Error "${{ inputs.netlify-toml-path }}" does not exist" >> $GITHUB_STEP_SUMMARY
+            echo "Error \"${{ inputs.netlify-toml-path }}\" does not exist" >> "$GITHUB_STEP_SUMMARY"
             exit 1
           fi
     - name: Update Netlify TOML
@@ -39,10 +39,10 @@ runs:
       run: |
           ## Update the Netlify TOML
           toml_updated=false
-          echo NETLIFY_TOML_UPDATED=$toml_updated >> $GITHUB_ENV
+          echo "NETLIFY_TOML_UPDATED=$toml_updated" >> "$GITHUB_ENV"
           if [ "${{ env.NETLIFY_CURRENT_VERSION }}" != "${{ env.HUGO_LATEST_VERSION }}" ]; then
-            sed -i.bak -e "s/HUGO_VERSION = .*/HUGO_VERSION = \"${{ env.HUGO_LATEST_VERSION }}\"/g" "${{ inputs.netlify-toml-path }}" && rm -f "${{ inputs.netlify-toml-path }}".bak
+            sed -i.bak -e "s/HUGO_VERSION\s*=\s*.*/HUGO_VERSION = \"${{ env.HUGO_LATEST_VERSION }}\"/g" "${{ inputs.netlify-toml-path }}" && rm -f "${{ inputs.netlify-toml-path }}".bak
             toml_updated=true
-            echo NETLIFY_TOML_UPDATED=$toml_updated >> $GITHUB_ENV
+            echo "NETLIFY_TOML_UPDATED=$toml_updated" >> "$GITHUB_ENV"
           fi
-          echo "Was the Netlify TOML Updated: $toml_updated" >> $GITHUB_STEP_SUMMARY
+          echo "Was the Netlify TOML Updated: $toml_updated" >> "$GITHUB_STEP_SUMMARY"
